#!/usr/bin/env bash
# Regenerate assets/js/catalog.js from products.json (Shopify catalog export).
# Local image files follow the pattern: assets/img/<handle><cdn-basename>
# Requires: jq
set -euo pipefail
cd "$(dirname "$0")/.."

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# 1) JSON set of local image basenames that actually exist on disk.
find assets/img -type f -exec basename {} \; \
  | jq -R -s 'split("\n") | map(select(length > 0))' > "$TMP"

# 2) Build the catalog array, keeping only images that exist locally.
{
  printf '/* GENERATED by scripts/build-catalog.sh — do not edit by hand. */\n'
  printf 'window.SIDIO_CATALOG='
  jq -c --slurpfile set "$TMP" '
    $set[0] as $have
    | def cat($h):
        if   ($h | startswith("lk"))                          then "lk"
        elif ($h | test("^tmat-|golf-cradle|velcro-|stacking-cups")) then "vehicle"
        elif ($h | test("mat$|red-full-mat|crate-base-mat")) then "vehicle"
        elif ($h | test("duffel|sleeve|cube|tech-pack|skate")) then "tech"
        elif ($h | test("divider|bamboo|polycarbonate|label|dry-erase|accessories|mystery|4-pack|seeding")) then "acc"
        else "crates" end;
    [ .products[] | . as $p
      | { h: $p.handle,
          t: $p.title,
          c: cat($p.handle),
          imgs: [ $p.images[].src
                  | (split("/") | last | split("?")[0]) as $b
                  | ($p.handle + $b)
                  | select(. as $f | ($have | index($f)) != null) ],
          o: [ $p.options[]? | { n: .name, v: .values } ],
          s: [ $p.variants[]
               | { o: [.option1, .option2, .option3],
                   p: (.price | tonumber),
                   a: (.available != false) } ]
        }
    ]' products.json
  printf ';'
} > assets/js/catalog.js

echo "wrote assets/js/catalog.js ($(wc -c < assets/js/catalog.js) bytes, $(jq 'length' "$TMP" >/dev/null; grep -o '"h":' assets/js/catalog.js | wc -l | tr -d ' ') products)"